(() => {
const sb=window.supabase.createClient(window.TSARANORO_SUPABASE_URL,window.TSARANORO_SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const ADMIN_EMAIL=window.TSARANORO_ADMIN_EMAIL||'tsaranoroo.admin@gmail.com'; const $=id=>document.getElementById(id); let hotels=[]; let pendingImages=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function size(n){return n>=1048576?(n/1048576).toFixed(1)+' MB':Math.ceil(n/1024)+' KB';}
function bar(msg,p){$('hUploadProgress').innerHTML=`<div class="progress"><b>${msg}</b><div class="track"><i style="width:${p}%"></i></div><span>${p}%</span></div>`;}
async function login(){const ident=$('adminId').value.trim();const pass=$('adminPass').value;const email=ident==='admin'?ADMIN_EMAIL:ident;const {error}=await sb.auth.signInWithPassword({email,password:pass});if(error){$('loginError').textContent='Identifiant ou mot de passe incorrect.';return;}showPanel();}
async function showPanel(){const {data:{user}}=await sb.auth.getUser();if(!user){$('loginBox').hidden=false;$('panel').hidden=true;return;}$('loginBox').hidden=true;$('panel').hidden=false;await loadHotels();}
async function logout(){await sb.auth.signOut();location.reload();}
async function loadHotels(){const {data,error}=await sb.from('hebergements').select('*').order('id');if(error){$('hotelList').innerHTML='<p>Erreur: '+esc(error.message)+'</p>';return;}hotels=data||[];renderHotels();}
function renderHotels(){ $('hotelList').innerHTML=hotels.map(x=>`<article class="hotel-card"><div class="thumb">${x.image_url?`<img src="${esc(x.image_url)}">`:'🏨'}</div><div><h3>${esc(x.nom)}</h3><button onclick="editHotel(${x.id})">✏️ Modifier</button><button class="danger" onclick="deleteHotel(${x.id})">🗑️ Supprimer</button></div></article>`).join('')||'<p>Aucun hébergement.</p>';}
function preview(){const box=$('hPhotoPreview');box.innerHTML=pendingImages.map((f,i)=>`<div class="file-row">📸 <span>${esc(f.name)} — ${size(f.size)}</span><button type="button" onclick="removePending(${i})">🗑️</button></div>`).join('');}
window.removePending=i=>{pendingImages.splice(i,1);preview();};
window.editHotel=id=>{const x=hotels.find(h=>h.id===id);if(!x)return;$('hotelForm').hidden=false;$('hId').value=x.id;$('hName').value=x.nom||'';$('hPhone').value=x.telephone||'';$('hWhatsApp').value=x.whatsapp||'';$('hWebsite').value=x.site_web||'';$('hPrice').value=x.prix||'Sur commande';$('hDesc').value=x.description||'';$('hServices').value=x.services||'';$('hPhotos').value='';$('hVideo').value='';pendingImages=[];preview();$('hUploadProgress').innerHTML='';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});};
window.newHotel=()=>{hotels.push({id:0,nom:'',actif:true});$('hotelForm').hidden=false;$('hId').value='';['hName','hPhone','hWhatsApp','hWebsite','hPrice','hDesc','hServices'].forEach(i=>$(i).value='');$('hPrice').value='Sur commande';pendingImages=[];preview();};
window.closeHotel=()=>{$('hotelForm').hidden=true;};
window.deleteHotel=async id=>{if(!confirm('Supprimer cet hébergement ?'))return;const {error}=await sb.from('hebergements').delete().eq('id',id);if(error)return alert(error.message);await loadHotels();};
$('hPhotos').onchange=e=>{pendingImages=[...e.target.files];preview();};
$('hotelForm').onsubmit=async e=>{e.preventDefault();const id=Number($('hId').value)||0;const old=hotels.find(h=>h.id===id);try{bar('Préparation...',0);let images=[...(old?.images||[])];if(!images.length&&old?.image_url)images=[old.image_url];for(let i=0;i<pendingImages.length;i++){const f=pendingImages[i];const p=Math.max(5,Math.round((i/(pendingImages.length+1))*85));bar(`📸 Upload image ${i+1}/${pendingImages.length} — ${f.name} (${size(f.size)})`,p);const path=`hotels/${Date.now()}-${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const q=await sb.storage.from('tsaranoro-media').upload(path,f,{contentType:f.type||undefined});if(q.error)throw q.error;images.push(sb.storage.from('tsaranoro-media').getPublicUrl(path).data.publicUrl);}let video_url=old?.video_url||null;const v=$('hVideo').files[0];if(v){bar(`🎥 Upload vidéo — ${v.name} (${size(v.size)})`,90);const path=`hotels/${Date.now()}-${crypto.randomUUID()}-${v.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const q=await sb.storage.from('tsaranoro-media').upload(path,v,{contentType:v.type||'video/mp4'});if(q.error)throw q.error;video_url=sb.storage.from('tsaranoro-media').getPublicUrl(path).data.publicUrl;}bar('💾 Enregistrement...',97);const payload={nom:$('hName').value.trim(),telephone:$('hPhone').value.trim(),whatsapp:$('hWhatsApp').value.trim(),site_web:$('hWebsite').value.trim(),prix:$('hPrice').value.trim()||'Sur commande',description:$('hDesc').value.trim(),services:$('hServices').value.trim(),images,image_url:images[0]||null,video_url,actif:old?.actif??true};const q=id?await sb.from('hebergements').update(payload).eq('id',id):await sb.from('hebergements').insert(payload);if(q.error)throw q.error;bar('✅ Upload terminé — fiche enregistrée',100);await loadHotels();setTimeout(closeHotel,600);}catch(err){$('hUploadProgress').innerHTML='<div class="error">❌ Échec de l’upload : '+esc(err.message||err)+'</div>';}};
window.login=login;window.logout=logout;showPanel();
})();