const SB = window.supabase.createClient(window.TSARANORO_SUPABASE_URL, window.TSARANORO_SUPABASE_KEY);
const ADMIN_EMAIL = window.TSARANORO_ADMIN_EMAIL;
const BUCKET = 'tsaranoro-media';
const tables = {hotel:'hebergements',activity:'activites',circuit:'circuits',guide:'guides',media:'galerie',reservation:'reservations'};
let state={hotels:[],activities:[],circuits:[],guides:[],media:[],reservations:[]};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function msg(t,ok=false){$('notice').innerHTML=`<div class="notice ${ok?'ok':'bad'}">${esc(t)}</div>`}
async function login(){const p=$('password').value.trim();const {error}=await SB.auth.signInWithPassword({email:ADMIN_EMAIL,password:p});if(error)return msg(error.message);await boot()}
async function logout(){await SB.auth.signOut();location.reload()}
async function boot(){const {data:{user}}=await SB.auth.getUser();if(!user){$('login').hidden=false;return}if(user.id!==window.TSARANORO_ADMIN_UID){await SB.auth.signOut();$('login').hidden=false;return}$('login').hidden=true;$('app').hidden=false;await loadAll()}
async function loadAll(){const names=['hotels','activities','circuits','guides','media','reservations'];const qs=await Promise.all(names.map(n=>SB.from(tables[n==='hotels'?'hotel':n==='activities'?'activity':n==='circuits'?'circuit':n==='guides'?'guide':n==='media'?'media':'reservation']).select('*').order('id',{ascending:false})));qs.forEach((q,i)=>{if(q.error)console.warn(names[i],q.error);state[names[i]]=q.data||[]});render()}
function tab(id,b){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('show'));$(id).classList.add('show');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')}
function render(){ $('counts').textContent=`${state.hotels.length} hôtels · ${state.activities.length} activités · ${state.circuits.length} circuits · ${state.guides.length} guides · ${state.media.length} médias · ${state.reservations.length} réservations`; renderHotels();renderActivities();renderCircuits();renderGuides();renderMedia();renderReservations() }
function card(x,type){const title=x.nom||x.titre||'Sans nom', image=x.image_url||((x.images||[])[0]);return `<article class="card">${image?`<a href="${esc(image)}" target="_blank"><img src="${esc(image)}"></a>`:''}<h3>${esc(title)}</h3><p>${esc(x.description||'')}</p><span class="pill">${x.actif===false?'Désactivé':'Actif'}</span><div><button onclick="edit('${type}',${x.id})">✏️ Modifier</button><button onclick="toggleItem('${type}',${x.id},${x.actif===false})">${x.actif===false?'▶️ Activer':'⏸️ Désactiver'}</button><button class="danger" onclick="delItem('${type}',${x.id})">🗑️ Supprimer</button></div></article>`}
function renderHotels(){$('hotelList').innerHTML=state.hotels.map(x=>card(x,'hotel')).join('')||'<p>Aucun hôtel.</p>'}
function renderActivities(){$('activityList').innerHTML=state.activities.map(x=>card(x,'activity')).join('')||'<p>Aucune activité.</p>'}
function renderCircuits(){$('circuitList').innerHTML=state.circuits.map(x=>card(x,'circuit')).join('')||'<p>Aucun circuit.</p>'}
function renderGuides(){$('guideList').innerHTML=state.guides.map(x=>card(x,'guide')).join('')||'<p>Aucun guide.</p>'}
function renderMedia(){$('mediaList').innerHTML=state.media.map(x=>`<article class="card">${x.type==='video'?`<video controls src="${esc(x.fichier_url)}"></video>`:`<a href="${esc(x.fichier_url)}" target="_blank"><img src="${esc(x.fichier_url)}"></a>`}<h3>${esc(x.titre)}</h3><button class="danger" onclick="delMedia(${x.id})">🗑️ Supprimer</button></article>`).join('')||'<p>Aucun média.</p>'}
function renderReservations(){$('reservationList').innerHTML=state.reservations.map(x=>`<article class="card"><h3>📅 ${esc(x.nom)}</h3><p>📱 ${esc(x.whatsapp||'—')} · 📧 ${esc(x.email||'—')}</p><p>📆 ${esc(x.date_souhaitee||'—')} · 👥 ${esc(x.nombre_personnes||'—')}</p><p>🥾/🏄 ${esc(x.type_reservation||'—')} · 🧭 ${esc(x.guide||'—')} · 🏨 ${esc(x.hotel||'—')}</p><p>${esc(x.message||'')}</p><b>${esc(x.statut||'Nouvelle')}</b><div><button onclick="setStatus(${x.id},'Confirmée')">✅ Confirmée</button><button onclick="setStatus(${x.id},'Refusée')">❌ Refusée</button><button onclick="setStatus(${x.id},'Nouvelle')">🆕 Nouvelle</button><button class="danger" onclick="delReservation(${x.id})">🗑️ Supprimer</button>${x.whatsapp?`<a target="_blank" href="https://wa.me/${esc(x.whatsapp.replace(/\D/g,''))}"><button>📱 WhatsApp</button></a>`:''}${x.email?`<a href="mailto:${esc(x.email)}"><button>📧 Email</button></a>`:''}</div></article>`).join('')||'<p>Aucune réservation.</p>'}
function edit(type,id=0){const x=(state[{hotel:'hotels',activity:'activities',circuit:'circuits',guide:'guides'}[type]]||[]).find(a=>a.id===id)||{};$('editor').innerHTML=form(type,x);$('editor').hidden=false;window.scrollTo({top:$('editor').offsetTop-20,behavior:'smooth'})}
function closeEditor(){$('editor').hidden=true;$('editor').innerHTML=''}
function form(type,x){let common='';if(type==='hotel')common=`<div class="grid"><label>🏨 Nom<input id="f_nom" value="${esc(x.nom)}"></label><label>📞 Téléphone<input id="f_tel" value="${esc(x.telephone)}"></label><label>WhatsApp<input id="f_wa" value="${esc(x.whatsapp)}"></label><label>🌐 Site web<input id="f_site" value="${esc(x.site_web)}"></label><label>💰 Tarif / Sur commande<input id="f_prix" value="${esc(x.prix||'Sur commande')}"></label><label class="full">📝 Description<textarea id="f_desc">${esc(x.description)}</textarea></label><label class="full">🛎️ Services<textarea id="f_services">${esc(x.services)}</textarea></label></div>`;if(type==='activity')common=`<div class="grid"><label>🏄 Nom<input id="f_nom" value="${esc(x.nom)}"></label><label>💰 Tarif / Sur commande<input id="f_prix" value="${esc(x.prix||'Sur demande')}"></label><label class="full">📝 Description<textarea id="f_desc">${esc(x.description)}</textarea></label><label class="full">🧰 Matériel<textarea id="f_mat">${esc(x.materiel)}</textarea></label><label class="full">📅 Disponibilité<textarea id="f_dispo">${esc(x.disponibilite)}</textarea></label><label>🔘 Bouton Réserver<select id="f_res"><option value="true" ${x.reserve_enabled!==false?'selected':''}>Afficher</option><option value="false" ${x.reserve_enabled===false?'selected':''}>Masquer</option></select></label></div>`;if(type==='circuit')common=`<div class="grid"><label>🥾 Nom<input id="f_nom" value="${esc(x.nom)}"></label><label>⏱️ Durée<input id="f_duree" value="${esc(x.duree)}"></label><label>🔴 Difficulté<input id="f_diff" value="${esc(x.difficulte)}"></label><label>💰 Tarif / Sur commande<input id="f_prix" value="${esc(x.prix||'Sur demande')}"></label><label class="full">📝 Description<textarea id="f_desc">${esc(x.description)}</textarea></label><label class="full">🗺️ Itinéraire<textarea id="f_itin">${esc(x.itinerary)}</textarea></label><label class="full">📍 Points importants<textarea id="f_points">${esc(x.points)}</textarea></label></div>`;if(type==='guide')common=`<div class="grid"><label>🧭 Nom<input id="f_nom" value="${esc(x.nom)}"></label><label>🗣️ Langues<input id="f_lang" value="${esc(x.langues)}"></label><label>⭐ Spécialités<input id="f_spec" value="${esc(x.specialites)}"></label><label class="full">📝 Description<textarea id="f_desc">${esc(x.description)}</textarea></label></div>`;return `<div class="editorBox"><h2>${type==='hotel'?'🏨 Hôtel':type==='activity'?'🏄 Activité':type==='circuit'?'🥾 Circuit':'🧭 Guide'}</h2>${common}<label class="upload">📸 Images ${type==='guide'?'':'maro'}<input id="photos" type="file" accept="image/*" multiple></label><label class="upload">🎥 Vidéo MP4<input id="video" type="file" accept="video/mp4,video/webm,video/quicktime"></label><div id="progress"></div><button class="save" onclick="save('${type}',${x.id||0})">💾 Enregistrer</button><button onclick="closeEditor()">Annuler</button></div>`}
async function save(type,id){try{const old=(state[{hotel:'hotels',activity:'activities',circuit:'circuits',guide:'guides'}[type]]||[]).find(x=>x.id===id)||{};let images=Array.isArray(old.images)?[...old.images]:[];for(const f of [...$('photos').files])images.push(await upload(f,`/${type}`));let video=old.video_url||old.video||null;if($('video').files[0])video=await upload($('video').files[0],`/${type}`);let p;if(type==='hotel')p={nom:$('f_nom').value,telephone:$('f_tel').value,whatsapp:$('f_wa').value,site_web:$('f_site').value,prix:$('f_prix').value,description:$('f_desc').value,services:$('f_services').value,images,image_url:images[0]||old.image_url||null,video_url:video,actif:old.actif!==false};if(type==='activity')p={nom:$('f_nom').value,prix:$('f_prix').value,description:$('f_desc').value,materiel:$('f_mat').value,disponibilite:$('f_dispo').value,reserve_enabled:$('f_res').value==='true',images,image_url:images[0]||old.image_url||null,video_url:video,actif:old.actif!==false};if(type==='circuit')p={nom:$('f_nom').value,duree:$('f_duree').value,difficulte:$('f_diff').value,prix:$('f_prix').value,description:$('f_desc').value,itinerary:$('f_itin').value,points:$('f_points').value,images,image_url:images[0]||old.image_url||null,video_url:video,actif:old.actif!==false};if(type==='guide')p={nom:$('f_nom').value,langues:$('f_lang').value,specialites:$('f_spec').value,description:$('f_desc').value,image_url:images[0]||old.image_url||null,actif:old.actif!==false};const table=tables[type];const q=id?await SB.from(table).update(p).eq('id',id):await SB.from(table).insert(p);if(q.error)throw q.error;closeEditor();await loadAll();msg('Enregistré avec succès.',true)}catch(e){msg(e.message)}}
async function upload(file,folder){const {data:{session}}=await SB.auth.getSession();const path=`${folder}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`${window.TSARANORO_SUPABASE_URL}/storage/v1/object/${BUCKET}/${path}`);xhr.setRequestHeader('apikey',window.TSARANORO_SUPABASE_KEY);xhr.setRequestHeader('Authorization',`Bearer ${session.access_token}`);xhr.upload.onprogress=e=>{if(e.lengthComputable){const n=Math.round(e.loaded/e.total*100);$('progress').innerHTML=`<div class="progress"><div class="track"><i style="width:${n}%"></i></div><b>${n}%</b> ${n===100?'Terminé':'Upload en cours...'}</div>`}};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve(`${window.TSARANORO_SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${path}`):reject(Error(`Upload ${xhr.status}`));xhr.onerror=()=>reject(Error('Erreur réseau upload'));xhr.send(file)})}
async function toggleItem(type,id,active){const q=await SB.from(tables[type]).update({actif:active}).eq('id',id);if(q.error)msg(q.error.message);else loadAll()}
async function delItem(type,id){if(!confirm('Supprimer cet élément ?'))return;const q=await SB.from(tables[type]).delete().eq('id',id);if(q.error)msg(q.error.message);else loadAll()}
async function addMedia(){const files=[...$('mediaFiles').files];for(const f of files){const url=await upload(f,'/gallery');const q=await SB.from('galerie').insert({titre:f.name,description:$('mediaDesc').value,type:f.type.startsWith('video/')?'video':'photo',fichier_url:url,actif:true});if(q.error)throw q.error}await loadAll()}
async function delMedia(id){if(confirm('Supprimer ce média ?')){await SB.from('galerie').delete().eq('id',id);loadAll()}}
async function setStatus(id,s){const q=await SB.from('reservations').update({statut:s}).eq('id',id);if(q.error)msg(q.error.message);else loadAll()}
async function delReservation(id){if(confirm('Supprimer la réservation ?')){await SB.from('reservations').delete().eq('id',id);loadAll()}}
window.login=login;window.logout=logout;window.tab=tab;window.edit=edit;window.closeEditor=closeEditor;window.save=save;window.toggleItem=toggleItem;window.delItem=delItem;window.addMedia=addMedia;window.delMedia=delMedia;window.setStatus=setStatus;window.delReservation=delReservation;
boot();